### ISSUE TITLE
[Q] Asymmetric input matrix

### ISSUE THREAD

**Issue by omaraflak** [letiantian/kmedoids#8]
Hey, thank you for sharing this code !

Can the algorithm handle a matrix of distances where `dist(A->B) != dist(B->A)` ?
i.e. an asymmetric distance matrix.

Thank you !

**Comment by TyrandeWhisperwind** [comment]
what is the tmax varaible for? and why did u set it to 100?
if i have a dataset of 800 points should i put tmax=800?
